name: CI - Cucumber Automation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run tests with Maven
        env:
          DISPLAY: ":99"
        run: |
          sudo Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          mvn clean test

      - name: Upload Extent Reports (if generated)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-reports
          path: |
            **/test-output/
            **/extent-reports/
            **/reports/
